# Generated by Django 4.0.3 on 2022-03-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raspis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raspis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('xona', models.PositiveSmallIntegerField(default=0)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raspis.kunlar')),
            ],
        ),
    ]
