# Generated by Django 4.0.3 on 2022-03-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspis', '0002_raspis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raspis',
            options={'ordering': ['raqam']},
        ),
        migrations.AlterField(
            model_name='raspis',
            name='xona',
            field=models.CharField(max_length=9),
        ),
    ]
